export default {
  id: "openai-web",
  alias: "openai-web",
  category: "oauth",
  authModes: ["oauth", "apikey"],
  hasOAuth: true,
  display: {
    name: "OpenAI Web",
    icon: "language",
    color: "#10A37F",
    textIcon: "OW",
    website: "https://chatgpt.com",
    notice: {
      signupUrl: "https://chatgpt.com",
    },
    deprecated: true,
    deprecationNotice: "RISK_NOTICE",
  },
  thinkingConfig: {
    options: [
      "auto",
      "none",
      "low",
      "medium",
      "high",
    ],
    defaultMode: "auto",
  },
  transport: {
    baseUrl: "https://chatgpt.com/backend-api/conversation",
    forceStream: true,
    clientVersion: "prod-a194cd50d4416d3c0b47c740f206b12ce60f5887",
    clientBuildNumber: "6708908",
  },
  models: [
    { id: "auto", name: "Auto" },
    { id: "gpt-5.6", name: "GPT 5.6" },
    { id: "gpt-5.5", name: "GPT 5.5" },
    { id: "gpt-5.4", name: "GPT 5.4" },
    { id: "gpt-5.3", name: "GPT 5.3" },
    { id: "gpt-5", name: "GPT 5" },
    { id: "gpt-4o", name: "GPT-4o" },
    { id: "gpt-4o-mini", name: "GPT-4o Mini" },
    { id: "gpt-4.1", name: "GPT-4.1" },
    { id: "o3", name: "O3" },
    { id: "o4-mini", name: "O4 Mini" },
    { id: "gpt-image-2", name: "GPT Image 2", capabilities: ["text2img"], params: ["n", "size", "quality", "response_format"], kind: "image" },
    { id: "gpt-image-2.5", name: "GPT Image 2.5", capabilities: ["text2img"], params: ["n", "size", "quality", "response_format"], kind: "image" },
    { id: "gpt-image-2.5-flare", name: "GPT Image 2.5 Flare", capabilities: ["text2img"], params: ["n", "size", "quality", "response_format"], kind: "image" },
    { id: "gpt-image-2.5-sunburst", name: "GPT Image 2.5 Sunburst", capabilities: ["text2img"], params: ["n", "size", "quality", "response_format"], kind: "image" },
  ],
  serviceKinds: ["llm", "image"],
  oauth: {
    clientId: "app_2SKx67EdpoN0G6j64rFvigXD",
    authorizeUrl: "https://auth.openai.com/api/accounts/authorize",
    tokenUrl: "https://auth.openai.com/api/accounts/oauth/token",
    issuer: "https://auth.openai.com",
    audience: "https://api.openai.com/v1",
    platformCallback: "https://platform.openai.com/auth/callback",
    auth0Client: "eyJuYW1lIjoiYXV0aDAtc3BhLWpzIiwidmVyc2lvbiI6IjEuMjEuMCJ9",
    scope: "openid profile email offline_access",
    codeChallengeMethod: "S256",
    refreshLeadMs: 86400000,
    refresh: {
      encoding: "json",
      scope: "openid profile email offline_access",
    },
    maxRefreshAgeMs: 2592000000,
    trackRefreshAt: true,
  },
  features: {
    usage: true,
  },
};
